models.py
import re
from app import db
from datetime import datetime
from time import time
from flask_security import UserMixin, RoleMixin


def slugify(s):
    pattern = r'[^\w+]'
    return re.sub(pattern, '-', s)


posts_tags = db.Table('posts_tags',
                      db.Column('post_id', db.Integer,
                      db.ForeignKey('post.id')),
                      db.Column('tag_id', db.Integer,
                      db.ForeignKey('tag.id'))
                      )

roles_users = db.Table('roles_users',
                       db.Column('user_id', db.Integer,
                       db.ForeignKey('user.id')),
                       db.Column('role_id', db.Integer,
                       db.ForeignKey('role.id'))
)


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), nullable=False)
    slug = db.Column(db.String(140), unique=True)
    body = db.Column(db.Text, nullable=False)
    created = db.Column(db.DateTime, default=datetime.now())
    video = db.Column(db.String(150))
    tags = db.relationship('Tag', secondary=posts_tags, backref=db.backref('posts'), lazy='dynamic')

    img_filename = db.Column(db.String())
    # img_data = db.Column(db.LargeBinary)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.generate_slug()

    def generate_slug(self):
        if self.title:
            self.slug = slugify(self.title)
        else:
            self.slug = str(int(time()))

    def __repr__(self):
        return f'<Post id: {self.id}, title: {self.title}>'


class Tag(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100))
    slug = db.Column(db.String(140), unique=True)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.slug = self.generate_slug()

    def generate_slug(self):
        if self.title:
            self.slug = slugify(self.title)
        else:
            self.slug = str(int(time()))

    def __repr__(self):
        return f'<Tag id: {self.id}, title: {self.title}>'


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(255))
    active = db.Column(db.Boolean)
    roles = db.relationship('Role', secondary=roles_users, backref=db.backref('users'), lazy='dynamic')


class Role(db.Model, RoleMixin):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), unique=True)

app.py
from flask import Flask, render_template, url_for, request, redirect, g, session, flash
from form_contact import ContactForm, csrf
from flask_mail import Mail, Message
from flask_admin import Admin, AdminIndexView
from flask_admin.contrib.sqla import ModelView
from flask_sqlalchemy import SQLAlchemy
from flask_security import SQLAlchemyUserDatastore, Security, current_user
from config import Config, mail_password, mail_username
from flask_migrate import Migrate
from flask_babelex import Babel


app = Flask(__name__)


babel = Babel(app)

csrf.init_app(app)
app.config.from_object(Config)


db = SQLAlchemy(app)
from models import *
migrate = Migrate(app, db)


class AdminMixin:
    def is_accessible(self):
        return current_user.has_role('admin')

    def inaccessible_callback(self, name, **kwargs):
        return redirect(url_for('security.login', next=request.url))


class AdminView(AdminMixin, ModelView):
    pass


class HomeAdminView(AdminMixin, AdminIndexView):
    pass


class BaseModelView(ModelView):
    def on_model_change(self, form, model, is_created):
        if is_created:
            model.generate_slug()
        return super().on_model_change(form, model, is_created)


class PostAdminView(AdminMixin, BaseModelView):
    pass


class TagAdminView(AdminMixin, BaseModelView):
    pass


admin = Admin(app, 'Гитара', url='/', index_view=HomeAdminView(name='Home'))

admin.add_view(PostAdminView(Post, db.session))
admin.add_view(TagAdminView(Tag, db.session))

app.config['MAIL_SERVER'] = 'smtp-mail.outlook.com'
app.config['MAIL_PORT'] = 587
app.config['MAIL_USERNAME'] = mail_username
app.config['MAIL_PASSWORD'] = mail_password
app.config['MAIL_USE_TLS'] = True
app.config['MAIL_USE_SSL'] = False
app.config['SESSION_COOKIE_SECURE'] = False

mail = Mail()
mail.init_app(app)


#Flask Security

user_datastore = SQLAlchemyUserDatastore(db, User, Role)
security = Security(app, user_datastore)


@babel.localeselector
def get_locale():
    if request.args.get('lang'):
        session['lang'] = request.args.get('lang')
    return session.get('lang', 'ru')


# @app.before_request
# def fix_missing_csrf_token():
#     if app.config['WTF_CSRF_FIELD_NAME'] not in session:
#         if app.config['WTF_CSRF_FIELD_NAME'] in g:
#             g.pop(app.config['WTF_CSRF_FIELD_NAME'])

main.py
from app import app
import views
from app import db
from posts.blueprint import posts


app.register_blueprint(posts, url_prefix='/blog')


if __name__ == '__main__':
    app.run(debug=False)

posts/blueprint.py
from flask import Blueprint, render_template
from models import *
from flask import request
from flask_security import login_required

posts = Blueprint('posts', __name__, template_folder='templates')


@posts.route('/')
def posts_list():
    q = request.args.get('q')
    if q:
        posts = Post.query.filter(Post.title.contains(q) |
                                  Post.body.contains(q))
    else:
        posts = Post.query.order_by(Post.created.desc())

    page = request.args.get('page')
    if page and page.isdigit():
        page = int(page)
    else:
        page = 1

    pages = posts.paginate(page=page, per_page=10)

    return render_template('posts/posts.html', posts=posts, pages=pages)


@posts.route('/<slug>')
def post_detail(slug):
    post = Post.query.filter(Post.slug==slug).first_or_404()
    return render_template('posts/post_detail.html', post=post)


@posts.route('/tags/<slug>')
def tag_detail(slug):
    tag = Tag.query.filter(Tag.slug==slug).first_or_404()
    return render_template('posts/tag_detail.html', tag=tag)

views.py
from app import app, mail
from flask import Flask, render_template, url_for, request, redirect, g, session, flash
from form_contact import ContactForm, csrf
from flask_mail import Mail, Message
from config import mail_username


@app.route("/")
def index():
    return render_template('index.html')


@app.route("/about")
def about():
    return render_template('about.html')


@app.route("/gallery")
def gallery():
    return render_template('gallery.html')


@app.route("/user/<string:name>/<int:id>")
def user(name, id):
    return f"Hello, {name}! Your ID is {id}."


@app.route('/contact', methods=['POST', 'GET'])
def contact():
    form = ContactForm()
    if form.validate_on_submit():
        send_message(request.form)
        return redirect('/success')

    return render_template('contact.html', form=form)


@app.route('/success')
def success():
    flash('Сообщение успешно отправлено!')
    return render_template('success.html')


@app.route('/robots.txt')
def robots():
    return 'User-agent: *\nAllow: /\n https://olgamaslova.onrender.com/contact/sitemap.xml'


@app.route('/sitemap.xml')
def sitemap():
    return render_template('sitemap.xml')


def send_message(message):
    text = 'Спасибо. Мы получили ваше письмо.\n\nТекст сообщения:\n' + message.get('message') + '\n\nОт кого: ' + message.get('name') + '\nEmail: ' + message.get('email')
    msg = Message(message.get('subject'), sender=mail_username,
            recipients=['canzonetta@mail.ru', message.get('email')],
            body=text
    )
    mail.send(msg)


@app.errorhandler(404)
def page_not_found(e):
    return render_template('404.html'), 404

posts/templates/posts/includes/cards.html
<div class="card my-5">
  <div class="card-header text-dark">
    <h5>{{ post.created.date() }}</h5>
  </div>
    <div class="container text-left">
  <div class="row">
    <div class="col">
  <div class="card-body">

    <h2 class="card-title"><a href="{{ url_for('posts.post_detail', slug=post.slug) }}">{{ post.title }}</a></h2>

    <a href="{{ url_for('posts.post_detail', slug=post.slug) }}" class="btn btn-light">Подробности</a>
  </div>
      </div>
    <div class="col">
        {% if post.video %}
      <iframe itemprop="subjectOf" itemscope itemtype="https://schema.org/VideoObject" class="w-100" height="185" src="{{ post.video }}" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</iframe>
        {% elif post.img_filename %}
<div class="card"><img class="img-thumbnail" src="{{post.img_filename}}"></div>
        {% endif %}
    </div>
        </div>
      </div>
            {% if post.tags.count() %}
            <div class="card-footer text-muted">
                {% for tag in post.tags %}
                    <a href="{{ url_for('posts.tag_detail', slug=tag.slug)}}"><span class="badge text-bg-info">{{ tag.title }}</span></a>
                {% endfor %}
            </div>
            {% endif %}
</div>

posts/templates/posts/includes/nav.html
 <form class="d-flex" role="search" method="GET">
        <input class="form-control me-2" type="search" placeholder="Поиск" aria-label="Search" name="q">
        <button class="btn btn-outline-success" type="submit">Поиск</button>
 </form>

posts/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block title %}
{{ post.title }}
{% endblock %}


{% block main %}
<div class="container my-3">
    <h1 class="pb-3 .text-primary" style="color:white">{{post.title}}</h1>

    {% if post.video %}
      <iframe class="w-100" height="500" src="{{ post.video }}" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</iframe>
        {% endif %}
    {% if post.img_filename %}
      <div class="card"><img class="card-img w-100 d-block" src="{{post.img_filename}}"></div>

        {% endif %}
<h3 class="my-5" style="color:white">{{post.body}}</h3>
</div>
{% endblock %}

posts/templates/posts/posts.html
{% extends 'base.html' %}

{% block title %}
Новости, статьи, видео
{% endblock %}

{% block nav %}
{% include 'posts/includes/nav.html' %}
{% endblock %}

{% block main %}
<div class="col-8 mx-auto">
<h1 class="pt-4">Видеоархив</h1>
    <h1>{% for post in pages.items %}
        {% include 'posts/includes/cards.html' %}
        {% endfor %}
    </h1>


<nav aria-label="...">
  <ul class="pagination">
    <li class="page-item {% if not pages.has_prev %} disabled {% endif %}">
      <a class="page-link" href="./?page={{ pages.prev_num }}">Предыдущая</a>
    </li>
      {% for page in pages.iter_pages() %}
        <li class="page-item {% if page==pages.page %} active {% endif %}">
            <a class="page-link" href="./?page={{page}}">{{ page }}</a>
        </li>

      {% endfor %}

    <li class="page-item {% if not pages.has_next %} disabled {% endif %}">
      <a class="page-link" href="./?page={{ pages.next_num }}">Следующая</a>
    </li>
  </ul>
</nav>
    </div>
{% endblock %}

posts/templates/posts/tag_detail.html
{% extends 'base.html' %}

{% block title %}
    Статьи с тегом '{{ tag.title }}'
{% endblock %}


{% block main %}
    <div class="container">

        <h1 class="my-5">Публикации с тегом '{{ tag.title }}'</h1>
    {% for post in tag.posts %}
        {% include 'posts/includes/cards.html' %}
    {% endfor %}
        </div>

{% endblock %}

templates/about.html
{% extends 'base.html' %}
{% block title %}
Обо мне
{% endblock %}
{% block main %}
<div class="container text-left">
  <div class="row">
    <div class="col">
      <h5 class="my-3"><strong>Провожу индивидуальные занятия по классу гитары:</strong> <br><br>

Уникальная программа обучения; <br>
Гитарная классика, песенный аккомпанемент; <br>
Обучение игре по нотам и табулатуре; <br>
Богатая нотная библиотека. <br><br>
<strong>О себе:</strong> <br> <br> Действующий преподаватель ДМШ по классу гитары с более чем 30-ти летним опытом преподавания,
          лауреат и призер конкурсов педагогического мастерства. <br>
За годы работы мною выпущено много учеников, имеющих дипломы лауреатов различных конкурсов и связавших свою жизнь с музыкой.
          <br>
Занятия проходят онлайн. Длительность урока 40 минут. <br><br>
      <strong>Уроки:</strong><br> <br>
          Занятия проходят онлайн. Длительность урока 40 минут.
          Все интересующие вопросы можно задать через <a href="/contact"> форму</a> обратной связи.<br> <br>


      </h5>
    </div>
    <div class="col">
      <div class="container">
    <h3 class="my-3" style="color:white">Lachapelle Claude <br>"Samba Cubana"</h3>
    <iframe class="my-3" width="450" height="330" src="https://www.youtube.com/embed/pvuRqv7l5ko" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</iframe>
</div>
    </div>
      </div>
    </div>



{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>
    <meta name="description" content="Провожу онлайн уроки игры на гитаре">
    <meta name="keywords" content="уроки гитары, уроки игры на гитаре, гитара с нуля уроки, музыкальная школа, как научиться играть на гитаре, онлайн уроки">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static', filename = 'assets/bootstrap/css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Work+Sans:300,400,500,700,800&amp;display=swap">
    <link rel="stylesheet" href="{{url_for('static', filename = 'assets/fonts/fontawesome-all.min.css')}}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/aosc.3.4/aos.css">
    <link rel="stylesheet" href="{{url_for('static', filename = 'assets/css/styles.css')}}">


    <script src="https://kit.fontawesome.com/e4299f24a1.js" crossorigin="anonymous"></script>

</head>

<body>

<nav class="navbar navbar-expand-lg bg-light sticky-top mb-1 " style= '--bs-bg-opacity: .8;'>
  <div class="container">
    <a class="navbar-brand" href="/">
      <img src="{{url_for('static', filename = 'assets/img/guitar2.png')}}" alt="Logo" width="40" height="35" class="d-inline-block align-text-top">

    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-md-end" id="navbarNav">
      <ul class="navbar-nav">

        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Главная</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{{url_for('posts.posts_list')}}">Видео</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="/gallery">Галерея</a>
        </li>
          <li class="nav-item">
              <li class="nav-item">
          <a class="nav-link" href="/about">Обо мне</a>
        </li>
          <a class="nav-link" href="/contact">Контакт</a>
        </li>
      </ul>
       {% block nav %}{% endblock %}
    </div>
  </div>
</nav>
<!-- Уроки гитары -->


{% block main %}{% endblock %}


    <footer class="mt-5 py-2">
        <div itemscope itemtype="https://schema.org/CreativeWork" class="container">
            <div class="row">
                <div class="col-md-6 text-center text-md-start d-md-flex justify-content-md-start align-items-md-center py-2">
                    <div>
                        <p itemprop="name" class="fs-5 fw-bold mb-0">Маслова Ольга<br></p>
                        <p class="mb-0">С <i class="fas fa-heart" style="color:red;"></i> из <span>Калининград</span>а<br></p>
                    </div>
                </div>
                <div class="col-md-6 d-flex justify-content-center align-items-center justify-content-md-end py-2">
                    <ul class="list-inline mb-0">
                        <li itemprop="url"  class="list-inline-item"><a href="https://vk.com/olga_canzonetta"  target="_blank"><i class="fa-brands fa-vk fs-1 me-2"></i></a></li>
                    <li itemprop="url"  class="list-inline-item"><a href="https://ok.ru/profile/538949607238"  target="_blank"><i class="fa-brands fa-square-odnoklassniki fs-1 me-2"></i></a></li>


                    <li itemprop="url"  class="list-inline-item"><a href="https://www.youtube.com/@user-eu1ri4yk9c"  target="_blank"><i class="fa-brands fa-youtube fs-1 me-2"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>

    <script src="./static/assets/bootstrap/js/bootstrap.min.js"></script>
    <script src="./static/assets/js/bs-init.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

</body>

</html>

templates/contact.html
{% extends "base.html" %}
{% block title %}
Контакты, форма обратной связи
{% endblock %}

{% block main %}

<div class="container w-50">

  <h1 class="pt-5">Форма обратной связи</h1>
<form action="{{ url_for('contact') }}" method="POST">
  {{ form.csrf_token }}

  <div class="form-group py-2">
    {{ form.name.label }}
    {{ form.name(class='form-control') }}
    {% for error in form.name.errors %}
    <span style="color: red;">[{{ error }}]</span>
    {% endfor %}
  </div>

  <div class="form-group py-2">
    {{ form.email.label }}
    {{ form.email(class='form-control') }}
    {% for error in form.email.errors %}
    <span style="color: red;">[{{ error }}]</span>
    {% endfor %}
  </div>

  <div class="form-group py-2">
    {{ form.subject.label }}
    {{ form.subject(class='form-control') }}
    {% for error in form.subject.errors %}
    <span style="color: red;">[{{ error }}]</span>
    {% endfor %}
  </div>

  <div class="form-group py-2 my-2">
    {{ form.message.label }}
    {{ form.message(class='form-control') }}
    {% for error in form.message.errors %}
    <span style="color: red;">[{{ error }}]</span>
    {% endfor %}
  </div>

  {{ form.submit(class='btn btn-success py-2') }}
  
</form>
</div>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block title %}
 Уроки игры на гитаре онлайн
{% endblock %}
{% block main %}
    <header>
        <div  itemscope itemtype="https://schema.org/CreativeWork" data-bss-parallax-bg="true" style="height: 600px;background-image: url(./static/assets/img/33.jpg);background-position: center;background-size: cover;">
            <div  class="container d-flex flex-column justify-content-end align-items-start">
                <h1 itemprop="name" class="display-3 fw-bold">Ольга Маслова<br></h1>
                <p class="fs-2 text-info text-badge mb-5"><span itemprop="educationalRole">Преподаватель</span> гитары<br></p>
            </div>
        </div>
    </header>
    <main>

        <section class="py-4 py-xl-5">
            <div class="container">
                <p itemprop="audience" itemscope itemtype="https://schema.org/EducationalAudience" class="fs-3"><span itemprop="educationalRole">Преподаватель по классу гитары</span> с более чем 30-ти летним опытом работы, лауреат и призер конкурсов педагогического мастерства.<br></p>
                <ul class="list-inline mb-0">
                    <li itemprop="url"  class="list-inline-item"><a href="https://vk.com/olga_canzonetta"  target="_blank"><i class="fa-brands fa-vk fs-1 me-2"></i></a></li>
                    <li itemprop="url" class="list-inline-item"><a href="https://ok.ru/profile/538949607238"  target="_blank"><i class="fa-brands fa-square-odnoklassniki fs-1 me-2"></i></a></li>


                    <li itemprop="url"  class="list-inline-item"><a href="https://www.youtube.com/@user-eu1ri4yk9c"  target="_blank"><i class="fa-brands fa-youtube fs-1 me-2"></i></a></li>
                </ul>
            </div>
        </section>

        <section class="py-4 py-xl-5">
            <div class="container">
                <div class="banner">
                    <p class="fs-1">Задать вопрос<br></p><a href="/contact"><button class="btn btn-dark btn-lg text-uppercase fw-bold" type="button">Связаться&nbsp;<i class="fas fa-chevron-right"></i></button></a>
                </div>
            </div>
        </section>
        <section class="py-4 py-xl-5">
            <div class="container" itemscope itemtype="https://schema.org/ImageObject">

          <a class="nav-link" href="/gallery"><h2 itemprop="name">Немного фото</h2></a>
        
                <div class="row row-cols-1 row-cols-md-2 row-cols-xl-3 py-5 projects">
                    <div class="col">
                        <div class="card"><img itemprop="contentUrl" class="card-img w-100 d-block" src="./static/assets/img/students/4.jpg"></div>
                    </div>
                    <div class="col">
                        <div class="card"><img itemprop="contentUrl" class="card-img w-100 d-block" style="hi" src="./static/assets/img/students/5.jpg"></div>
                    </div>
                    <div class="col">
                        <div class="card"><img itemprop="contentUrl" class="card-img w-100 d-block" src="./static/assets/img/students/3.jpg"></div>
                    </div>
                    <div class="col">
                        <div class="card"><img itemprop="contentUrl" class="card-img w-100 d-block" src="./static/assets/img/students/2.jpg"></div>
                    </div>
                    <div class="col">
                        <div class="card"><img itemprop="contentUrl" class="card-img w-100 d-block" src="./static/assets/img/students/1.jpg"></div>
                    </div>
                    <div class="col">
                        <div class="card"><img itemprop="contentUrl" class="card-img w-100 d-block" src="./static/assets/img/students/6.jpg"></div>
                    </div>
                </div>
            </div>
        </section>
    </main>
{% endblock %}

templates/security/_messages.html
{%- with messages = get_flashed_messages(with_categories=true) -%}
  {% if messages %}
    <div class="flashes">
    {% for category, message in messages %}
      <div class="alert alert-category {{ category }}">{{ message }}</div>
    {% endfor %}
    </div>
  {% endif %}
{%- endwith %}

templates/security/login_user.html
{% extends 'base.html' %}
{% block title %}
Регистрация
{% endblock %}
{% block main %}
<div class="container">

{% from "security/_macros.html" import render_field_with_errors, render_field %}
{% include "security/_messages.html" %}
<h1>{{ ('Регистрация') }}</h1>
<form action="{{ url_for_security('login') }}" method="POST" name="login_user_form">
  {{ login_user_form.hidden_tag() }}
  {{ render_field_with_errors(login_user_form.email, class = 'form-control') }}
  {{ render_field_with_errors(login_user_form.password, class = 'form-control') }}
  {{ render_field_with_errors(login_user_form.remember) }}
  {{ render_field(login_user_form.next) }}
  {{ render_field(login_user_form.submit, class = 'btn btn-success') }}
</form>
{% include "security/_menu.html" %}
  </div>
{% endblock %}

templates/success.html
{% extends 'base.html' %}
{% block title %}
Подтверждение отправки сообщения
{% endblock %}
{% block main %}
<div class="container">
    {% for msg in get_flashed_messages()%}


   <div class="card w-50 m-5">
  <div class="card-body">
    <h5 class="card-title text-primary">Подтверждение</h5>
    <p class="card-text text-info">{{msg}}</p>
    <a href="/" class="btn btn-primary">На главную</a>
  </div>
</div>
    {% endfor %}

</div>
{% endblock %}